ignore:
  - '^\.pathogen\.yml'
  - '^README\.md$'
variables:
  - name: serviceName
    description: the name of the service making egress requests
    value:
  - name: egressServiceName
    description: the name of the service to make requests to
    value:
  - name: trustDomain
    description: the trust domain for SPIRE
    value: quickstart.greymatter.io
  - name: path
    description: the path for the route to egressService
    value:
  - name: zone
    description: the zone in which the sidecar runs
    value: zone-default-zone