ignore:
  - '^\.pathogen\.yml'
  - '^README\.md$'
variables:
  - name: serviceName
    description: serviceName (the name of the service and sidecar)
    value:
  - name: sidecarIngressPort
    description: sidecarIngressPort (the port on which the sidecar listens for ingress connections)
    value: 10808
  - name: servicePort
    description: servicePort (the port on which the service listens)
    value: 8080
  - name: zone
    description: zone (the zone in which the sidecar runs)
    value: zone-default-zone
  - name: fabricNamespace
    description: fabricNamespace (the kubernetes namespace where Grey Matter Control is running)
    value: default
  - name: image
    description: image (the image for your new service)
    value: docker.greymatter.io/internal/fibonacci:latest
  - name: controlPodLabel
    description: controlPodLabel (the value of `gm_control_kubernetes_cluster_label` environment variable for gm-control)
    value: greymatter.io/control
