ignore:
  - '^\.pathogen\.yml'
  - '^README\.md$'
variables:
  - name: serviceName
    description: the service name to route to from edge
    value:
  - name: trustDomain
    description: the trust domain for SPIRE
    value: quickstart.greymatter.io
  - name: zone
    description: the zone in which the sidecar runs
    value: zone-default-zone
