ignore:
  - '^\.pathogen\.yml'
  - '^README\.md$'
variables:
  - name: serviceName
    description: serviceName (the name of the service and sidecar to route to from edge)
    value:
  - name: trustDomain
    description: trustDomain (the trust domain for SPIRE)
    value: quickstart.greymatter.io
  - name: zone
    description: zone (the zone in which the sidecar runs)
    value: zone-default-zone
